######################################################################
# Automatically generated by qmake (2.01a) Sun Aug 19 17:02:26 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += 6-1code.cpp
